### ISSUE TITLE
Extraction does not work for<meaning> with postfix

### ISSUE THREAD

**Issue by lukwas314** [tsvetomir/xlf-extract#2]
Extract does not work properly in this exxample
`
<input placeholder="test.value" i18n-placeholder="test.value|Test value label" />
<span i18n="test.value.required|Test value required info">test.value.required</span>
`

only **test.value** will be extracted

**Comment by tsvetomir** [comment]
Only leaf nodes can contain messages. This is due to the structure of the YAML document, to illustrate:

```yaml
# "test" is a dictionary
test:
  # "value" is a string
  value: test.value
    # Not valid: can't add a key/value pair to a string
    required: test.value.required
```

To get around that place the messages on the same level:
```html
<input placeholder="test.value" i18n-placeholder="test.value.label|Test value label" />
<span i18n="test.value.required|Test value required info">test.value.required</span>
```
